name: Dummy workflow
run-name: ${{ github.actor }} is testing Snakemake
on: [push, workflow_dispatch]
jobs:
  basic-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Linting
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: '.test'
          snakefile: 'workflow/Snakefile'
          args: '--lint'
      - name: Testing
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: '.test'
          snakefile: 'workflow/Snakefile'
          args: '--cores 1 --use-conda --conda-cleanup-pkgs cache'
