config: "config.yaml"

rule all:
    input:
        expand("results/analysis/{outfile}.txt",
               outfile = config["dataset"])

rule dummy:
    # input:
    output:
        expand("results/analysis/{outfile}.txt")
    log:
        "results/log/"
    shell:
        "echo {wildcards.outfile} > {output}"
