language: node_js
node_js:
  - v18
  - v16
  - v14
  - v12
  - v10
  - v8
  - v6
  - v4
before_script:
  - 'git config --global user.email "francesco.tabaro@gmail.com"'
  - 'git config --global user.name "Francesco Tabaro"'
after_script: cat ./coverage/lcov.info | coveralls
